//-----------------------------------------
//
// Generated by nedtool, version 3.3
// date: Wed Jan 02 21:20:12 2008
//
//-----------------------------------------


#include <math.h>
#include "omnetpp.h"

// NEDC version check
#define NEDC_VERSION 0x0303
#if (NEDC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedc: 'make clean' should help.
#endif

// Disable warnings about unused variables. For MSVC and BC only:
// GCC has no way to turn on its -Wunused option in a source file :(
#ifdef _MSC_VER
#  pragma warning(disable:4101)
#endif
#ifdef __BORLANDC__
#  pragma warn -waus
#  pragma warn -wuse
#endif

static cModuleType *_getModuleType(const char *modname)
{
    cModuleType *modtype = findModuleType(modname);
    if (!modtype)
        throw new cRuntimeError("Module type definition %s not found (Define_Module() missing from C++ code?)", modname);
    return modtype;
}

static void _checkModuleVectorSize(int vectorsize, const char *mod)
{
    if (vectorsize<0)
        throw new cRuntimeError("Negative module vector size %s[%d]", mod, vectorsize);
}

static void _readModuleParameters(cModule *mod)
{
    int n = mod->params();
    for (int k=0; k<n; k++)
        if (mod->par(k).isInput())
            mod->par(k).read();
}

static int _checkModuleIndex(int index, int vectorsize, const char *modname)
{
    if (index<0 || index>=vectorsize)
        throw new cRuntimeError("Submodule index %s[%d] out of range, sizeof(%s) is %d", modname, index, modname, vectorsize);
    return index;
}

static cGate *_checkGate(cModule *mod, const char *gatename)
{
    cGate *g = mod->gate(gatename);
    if (!g)
        throw new cRuntimeError("%s has no gate named %s",mod->fullPath().c_str(), gatename);
    return g;
}

static cGate *_checkGate(cModule *mod, const char *gatename, int gateindex)
{
    cGate *g = mod->gate(gatename, gateindex);
    if (!g)
        throw new cRuntimeError("%s has no gate %s[%d]",mod->fullPath().c_str(), gatename, gateindex);
    return g;
}

static cGate *_getFirstUnusedParentModGate(cModule *mod, const char *gatename)
{
    int baseId = mod->findGate(gatename);
    if (baseId<0)
        throw new cRuntimeError("%s has no %s[] gate",mod->fullPath().c_str(), gatename);
    int n = mod->gate(baseId)->size();
    for (int i=0; i<n; i++)
        if (!mod->gate(baseId+i)->isConnectedInside())
            return mod->gate(baseId+i);
    throw new cRuntimeError("%s[] gates are all connected, no gate left for `++' operator",mod->fullPath().c_str(), gatename);
}

static cGate *_getFirstUnusedSubmodGate(cModule *mod, const char *gatename)
{
    int baseId = mod->findGate(gatename);
    if (baseId<0)
        throw new cRuntimeError("%s has no %s[] gate",mod->fullPath().c_str(), gatename);
    int n = mod->gate(baseId)->size();
    for (int i=0; i<n; i++)
        if (!mod->gate(baseId+i)->isConnectedOutside())
            return mod->gate(baseId+i);
    int newBaseId = mod->setGateSize(gatename,n+1);
    return mod->gate(newBaseId+n);
}

static cFunctionType *_getFunction(const char *funcname, int argcount)
{
    cFunctionType *functype = findFunction(funcname,argcount);
    if (!functype)
        throw new cRuntimeError("Function %s with %d args not found", funcname, argcount);
    return functype;
}

static cChannel *_createChannel(const char *channeltypename)
{
    cChannelType *channeltype = findChannelType(channeltypename);
    if (!channeltype)
        throw new cRuntimeError("Channel type %s not found", channeltypename);
    cChannel *channel = channeltype->create("channel");
    return channel;
}

static cChannel *_createNonTypedBasicChannel(double delay, double error, double datarate)
{
    cBasicChannel *channel = new cBasicChannel("channel");
    if (delay!=0) channel->setDelay(delay);
    if (error!=0) channel->setError(error);
    if (datarate!=0) channel->setDatarate(datarate);
    return channel;
}

static cXMLElement *_getXMLDocument(const char *fname, const char *pathexpr=NULL)
{
    cXMLElement *node = ev.getXMLDocument(fname, pathexpr);
    if (!node)
        throw new cRuntimeError(!pathexpr ? "xmldoc(\"%s\"): element not found" : "xmldoc(\"%s\", \"%s\"): element not found",fname,pathexpr);
    return node;
}

ModuleInterface(PC)
    // gates:
    Gate(in[], GateDir_Input)
    Gate(out[], GateDir_Output)
EndInterface

Register_ModuleInterface(PC)

//// Sample code:
// class PC : public cSimpleModule
// {
//     Module_Class_Members(PC,cSimpleModule,16384)
//     virtual void activity();
//     // Add you own member functions here!
// };
//
// Define_Module(PC);
//
// void PC::activity()
// {
//     // Put code for simple module activity here!
// }
//

ModuleInterface(PacketFilter1)
EndInterface

Register_ModuleInterface(PacketFilter1);

class PacketFilter1 : public cCompoundModule
{
  public:
    PacketFilter1() : cCompoundModule() {}
  protected:
    virtual void doBuildInside();
};

Define_Module(PacketFilter1);

void PacketFilter1::doBuildInside()
{
    cModule *mod = this;

    // temporary variables:
    cPar tmpval;
    const char *modtypename;

    // submodules:
    cModuleType *modtype = NULL;
    int submodindex;

    //
    // submodule 'PC':
    //
    int PC_size = (int)(4);
    _checkModuleVectorSize(PC_size,"PC");
    cModule **PC_p = new cModule *[PC_size];
    if (PC_size>0)
    {
        modtype = _getModuleType("PC");
    }
    for (submodindex=0; submodindex<PC_size; submodindex++)
    {
        PC_p[submodindex] = modtype->create("PC", mod, PC_size, submodindex);
        cContextSwitcher __ctx(PC_p[submodindex]); // do the rest in this module's context

        _readModuleParameters(PC_p[submodindex]);
        PC_p[submodindex]->setDisplayString("i=device/pc3");
    }

    //
    // connections:
    //
    cGate *srcgate, *destgate;

    cChannel *channel;
    cPar *par;
    // connection
    srcgate = _getFirstUnusedSubmodGate(PC_p[_checkModuleIndex((int)(0),PC_size,"PC")], "out");
    destgate = _getFirstUnusedSubmodGate(PC_p[_checkModuleIndex((int)(2),PC_size,"PC")], "in");
    channel = _createNonTypedBasicChannel(0.1, 0, 0);
    srcgate->connectTo(destgate,channel);

    // connection
    srcgate = _getFirstUnusedSubmodGate(PC_p[_checkModuleIndex((int)(2),PC_size,"PC")], "out");
    destgate = _getFirstUnusedSubmodGate(PC_p[_checkModuleIndex((int)(0),PC_size,"PC")], "in");
    channel = _createNonTypedBasicChannel(0.1, 0, 0);
    srcgate->connectTo(destgate,channel);

    // connection
    srcgate = _getFirstUnusedSubmodGate(PC_p[_checkModuleIndex((int)(1),PC_size,"PC")], "out");
    destgate = _getFirstUnusedSubmodGate(PC_p[_checkModuleIndex((int)(2),PC_size,"PC")], "in");
    channel = _createNonTypedBasicChannel(0.1, 0, 0);
    srcgate->connectTo(destgate,channel);

    // connection
    srcgate = _getFirstUnusedSubmodGate(PC_p[_checkModuleIndex((int)(2),PC_size,"PC")], "out");
    destgate = _getFirstUnusedSubmodGate(PC_p[_checkModuleIndex((int)(1),PC_size,"PC")], "in");
    channel = _createNonTypedBasicChannel(0.1, 0, 0);
    srcgate->connectTo(destgate,channel);

    // connection
    srcgate = _getFirstUnusedSubmodGate(PC_p[_checkModuleIndex((int)(2),PC_size,"PC")], "out");
    destgate = _getFirstUnusedSubmodGate(PC_p[_checkModuleIndex((int)(3),PC_size,"PC")], "in");
    channel = _createNonTypedBasicChannel(0.1, 0, 0);
    srcgate->connectTo(destgate,channel);

    // connection
    srcgate = _getFirstUnusedSubmodGate(PC_p[_checkModuleIndex((int)(3),PC_size,"PC")], "out");
    destgate = _getFirstUnusedSubmodGate(PC_p[_checkModuleIndex((int)(2),PC_size,"PC")], "in");
    channel = _createNonTypedBasicChannel(0.1, 0, 0);
    srcgate->connectTo(destgate,channel);

    // check all gates are connected:
    mod->checkInternalConnections();


    //
    // this level is done -- recursively build submodules too
    //
    for (submodindex=0; submodindex<PC_size; submodindex++)
        PC_p[submodindex]->buildInside();
    delete [] PC_p;
}

class PacketFilter : public cNetworkType
{
  public:
    PacketFilter(const char *name) : cNetworkType(name) {}
    PacketFilter(const PacketFilter& n) : cNetworkType(n.name()) {operator=(n);}
    virtual void setupNetwork();
};

Define_Network(PacketFilter);

void PacketFilter::setupNetwork()
{
    // temporary variables:
    cPar tmpval;
    const char *modtypename;

    cModuleType *modtype;

    modtype = _getModuleType("PacketFilter1");
    cModule *PacketFilter_p = modtype->create("PacketFilter", NULL);

    cContextSwitcher __ctx(PacketFilter_p); // do the rest in this module's context
    _readModuleParameters(PacketFilter_p);
    // build submodules recursively (if it has any):
    PacketFilter_p->buildInside();
}

