//
// Generated file, do not edit! Created by opp_msgc 3.3 from rndMessage.msg.
//

#ifndef _RNDMESSAGE_M_H_
#define _RNDMESSAGE_M_H_

#include <omnetpp.h>

// opp_msgc version check
#define MSGC_VERSION 0x0303
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgc: 'make clean' should help.
#endif


/**
 * Class generated from <tt>rndMessage.msg</tt> by opp_msgc.
 * <pre>
 * message rndMessage
 * {
 *     fields:
 *         int source;
 *         int destination;
 * }
 * </pre>
 */
class rndMessage : public cMessage
{
  protected:
    int source_var;
    int destination_var;

    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const rndMessage&);

  public:
    rndMessage(const char *name=NULL, int kind=0);
    rndMessage(const rndMessage& other);
    virtual ~rndMessage();
    rndMessage& operator=(const rndMessage& other);
    virtual cPolymorphic *dup() const {return new rndMessage(*this);}
    virtual void netPack(cCommBuffer *b);
    virtual void netUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual int getSource() const;
    virtual void setSource(int source_var);
    virtual int getDestination() const;
    virtual void setDestination(int destination_var);
};

inline void doPacking(cCommBuffer *b, rndMessage& obj) {obj.netPack(b);}
inline void doUnpacking(cCommBuffer *b, rndMessage& obj) {obj.netUnpack(b);}

#endif // _RNDMESSAGE_M_H_
